import Link from 'next/link';
import { Sparkles, Sun, Newspaper, Brain, Swords, Trophy, Target, BookOpen, CheckCircle2, Users, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function LandingPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            '@context': 'https://schema.org',
            '@type': 'WebApplication',
            name: 'Morning Briefing',
            url: 'https://daily-briefing-lime.vercel.app',
            description: 'A personalized daily briefing dashboard with weather, news, habits, journaling, community leaderboards, and AI-powered insights.',
            applicationCategory: 'LifestyleApplication',
            operatingSystem: 'Web',
            offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
          }),
        }}
      />
      <div className="min-h-screen flex flex-col">
        <header className="border-b border-border">
          <div className="max-w-7xl mx-auto px-6 py-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <Sparkles className="w-6 h-6 text-primary" />
              <span className="font-serif text-xl font-bold">Morning Briefing</span>
            </div>
            <div className="flex items-center gap-4">
              <Link href="/auth/login">
                <Button variant="ghost">Sign In</Button>
              </Link>
              <Link href="/auth/signup">
                <Button>Get Started Free</Button>
              </Link>
            </div>
          </div>
        </header>

        <main className="flex-1">
          {/* Hero */}
          <section className="max-w-7xl mx-auto px-6 py-24 md:py-32">
            <div className="max-w-3xl">
              <h1 className="font-serif text-5xl md:text-7xl font-bold leading-tight mb-6">
                Your morning.
                <br />
                <span className="text-primary">Personalized.</span> Intelligent.
              </h1>
              <p className="text-lg md:text-xl text-text-secondary mb-10 max-w-xl leading-relaxed">
                A daily ritual that brings together weather, news, habits, journaling, 
                community leaderboards, and AI-powered insights&mdash;all in one beautiful page. 
                Start each day with clarity.
              </p>
              <div className="flex flex-wrap gap-4">
                <Link href="/auth/signup">
                  <Button size="lg" className="text-base px-8 py-6 h-auto">
                    Start Your Morning Ritual
                  </Button>
                </Link>
                <Link href="/auth/login">
                  <Button variant="outline" size="lg" className="text-base px-8 py-6 h-auto">
                    Sign In
                  </Button>
                </Link>
              </div>
            </div>
          </section>

          {/* Features Grid */}
          <section className="border-t border-border py-20">
            <div className="max-w-7xl mx-auto px-6">
              <h2 className="font-serif text-3xl font-bold text-center mb-12">
                Everything you need to start your day right
              </h2>
              <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
                <FeatureCard
                  icon={<Sun className="w-6 h-6" />}
                  title="Weather & Calendar"
                  description="Real-time weather forecasts and Google Calendar events at a glance."
                />
                <FeatureCard
                  icon={<Target className="w-6 h-6" />}
                  title="Daily Focus"
                  description="Set 3 priority tasks each day with progress tracking and XP rewards."
                />
                <FeatureCard
                  icon={<CheckCircle2 className="w-6 h-6" />}
                  title="Habit Tracking"
                  description="Build streaks with visual weekly calendars and emoji-powered habits."
                />
                <FeatureCard
                  icon={<Newspaper className="w-6 h-6" />}
                  title="Curated News"
                  description="Stay informed with news tailored to your interests from 8 topics."
                />
                <FeatureCard
                  icon={<BookOpen className="w-6 h-6" />}
                  title="Journal Prompts"
                  description="Daily writing prompts with auto-save and word count tracking."
                />
                <FeatureCard
                  icon={<Brain className="w-6 h-6" />}
                  title="AI Insights"
                  description="Personal daily reflections generated by Claude AI based on your activity."
                />
                <FeatureCard
                  icon={<Swords className="w-6 h-6" />}
                  title="Community"
                  description="Add friends, compete on leaderboards, and climb the global rankings."
                />
                <FeatureCard
                  icon={<Trophy className="w-6 h-6" />}
                  title="32 Achievements"
                  description="Unlock Bronze to Platinum trophies for tasks, streaks, habits, and more."
                />
                <FeatureCard
                  icon={<Zap className="w-6 h-6" />}
                  title="XP & Levels"
                  description="Earn XP for every action, level up from Newcomer to Mythic."
                />
              </div>
            </div>
          </section>

          {/* Community / Social Proof */}
          <section className="border-t border-border py-20 bg-surface/20">
            <div className="max-w-7xl mx-auto px-6 text-center">
              <h2 className="font-serif text-3xl font-bold mb-4">Compete and connect</h2>
              <p className="text-text-secondary mb-12 max-w-lg mx-auto">
                Add friends, compare streaks, climb the global leaderboard, 
                and unlock achievements together.
              </p>
              <div className="grid md:grid-cols-3 gap-8 max-w-3xl mx-auto">
                <div className="p-6 rounded-2xl border border-border bg-card">
                  <Users className="w-8 h-8 text-primary mx-auto mb-3" />
                  <p className="text-2xl font-bold">Friends</p>
                  <p className="text-sm text-text-secondary">Add & compete</p>
                </div>
                <div className="p-6 rounded-2xl border border-border bg-card">
                  <Trophy className="w-8 h-8 text-primary mx-auto mb-3" />
                  <p className="text-2xl font-bold">Leaderboards</p>
                  <p className="text-sm text-text-secondary">Global & friends</p>
                </div>
                <div className="p-6 rounded-2xl border border-border bg-card">
                  <Sparkles className="w-8 h-8 text-primary mx-auto mb-3" />
                  <p className="text-2xl font-bold">32 Badges</p>
                  <p className="text-sm text-text-secondary">Bronze to Platinum</p>
                </div>
              </div>
            </div>
          </section>

          {/* CTA */}
          <section className="border-t border-border py-20">
            <div className="max-w-7xl mx-auto px-6 text-center">
              <h2 className="font-serif text-3xl font-bold mb-4">
                Start your ritual today
              </h2>
              <p className="text-text-secondary mb-8 max-w-md mx-auto">
                Free forever. No credit card required.
              </p>
              <Link href="/auth/signup">
                <Button size="lg" className="text-base px-10 py-6 h-auto">
                  Get Started Free
                </Button>
              </Link>
            </div>
          </section>
        </main>

        <footer className="border-t border-border py-8">
          <div className="max-w-7xl mx-auto px-6 flex flex-col md:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-2 text-sm text-text-secondary">
              <Sparkles className="w-4 h-4 text-primary" />
              Morning Briefing &mdash; Start each day with intention.
            </div>
            <div className="flex items-center gap-6 text-sm">
              <Link href="/privacy" className="text-text-secondary hover:text-foreground transition-colors">Privacy</Link>
              <Link href="/terms" className="text-text-secondary hover:text-foreground transition-colors">Terms</Link>
              <Link href="/changelog" className="text-text-secondary hover:text-foreground transition-colors">Changelog</Link>
              <Link href="/api/health" className="text-text-secondary hover:text-foreground transition-colors">Status</Link>
              <Link href="/auth/login" className="text-text-secondary hover:text-foreground transition-colors">Sign In</Link>
            </div>
          </div>
        </footer>
      </div>
    </>
  );
}

function FeatureCard({ icon, title, description }: { icon: React.ReactNode; title: string; description: string }) {
  return (
    <div className="p-6 rounded-2xl border border-border bg-card hover:border-primary/30 transition-colors">
      <div className="text-primary mb-3">{icon}</div>
      <h3 className="font-serif text-lg font-semibold mb-2">{title}</h3>
      <p className="text-sm text-text-secondary leading-relaxed">{description}</p>
    </div>
  );
}
